name: Publish Docs

on:
  push:
    paths-ignore:
      - "docs/**"
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        check-latest: true
    - run: npm install && npx vuepress build .
    - name: Publish Docs
      run: |
        git add .
        git commit -am "github actions generate docs on : $(date +"%Y-%m-%d %T")"
        git push
